name: morgan-stanley-hackathon-2024

services:
  frontend:
    build: frontend
    networks:
      - internal
    ports:
      - 8000:8000
    environment:
      - WEB_PORT=8000
      - VITE_BACCKEND_BASE_URL=backend:80
  backend:
    build: backend
    networks:
      - internal
    ports:
      - 80:80
    environment:
      - FLASK_RUN_PORT=80
    volumes:
      - ./backend/instance:/app/instance

networks:
  internal:
